// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2EuGniFd_OhvxpquX_6O0pGjbtms-9wk',
    appId: '1:42873329743:web:4874c1ea027c5d9406723a',
    messagingSenderId: '42873329743',
    projectId: 'pawtique3-85ed4',
    authDomain: 'pawtique3-85ed4.firebaseapp.com',
    databaseURL: 'https://pawtique3-85ed4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pawtique3-85ed4.firebasestorage.app',
    measurementId: 'G-S7JTCQYWDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs153hTWETyPAQC6b6YIGxj3AdWArrqc4',
    appId: '1:42873329743:android:002a11981ce7222306723a',
    messagingSenderId: '42873329743',
    projectId: 'pawtique3-85ed4',
    databaseURL: 'https://pawtique3-85ed4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pawtique3-85ed4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYQ3-fwmGRLwIk8IHqNj-BSpXhFG0P7V8',
    appId: '1:42873329743:ios:e446c0aa92c1c9d606723a',
    messagingSenderId: '42873329743',
    projectId: 'pawtique3-85ed4',
    databaseURL: 'https://pawtique3-85ed4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pawtique3-85ed4.firebasestorage.app',
    iosBundleId: 'com.example.pawtique3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYQ3-fwmGRLwIk8IHqNj-BSpXhFG0P7V8',
    appId: '1:42873329743:ios:e446c0aa92c1c9d606723a',
    messagingSenderId: '42873329743',
    projectId: 'pawtique3-85ed4',
    databaseURL: 'https://pawtique3-85ed4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pawtique3-85ed4.firebasestorage.app',
    iosBundleId: 'com.example.pawtique3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2EuGniFd_OhvxpquX_6O0pGjbtms-9wk',
    appId: '1:42873329743:web:f8e9783417b7909606723a',
    messagingSenderId: '42873329743',
    projectId: 'pawtique3-85ed4',
    authDomain: 'pawtique3-85ed4.firebaseapp.com',
    databaseURL: 'https://pawtique3-85ed4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pawtique3-85ed4.firebasestorage.app',
    measurementId: 'G-T136SDP4HC',
  );
}
